### ISSUE TITLE
Upload files to the root directory：422

### ISSUE THREAD

**Issue by nanarino** [DimCyan/ffserver#1]
Win 10，Python 3.8.2
Microsoft Edge 99.0.1150.30
while upload files to the root directory：
INFO:     127.0.0.1:60858 - "POST /upload/uploader HTTP/1.1" 422 Unprocessable Entity

**Comment by DimCyan** [comment]
Thx for this issue, and I fixed it by the latest commit. Enjoy it and have a good day! 😊
